#!/bin/bash

#SBATCH --account=updalpe
#SBATCH --job-name=REPLACEME1

#SBATCH --time=23:59:00
#SBATCH --nodes=8
#SBATCH --ntasks=128
#SBATCH --cpus-per-task=1

source /ssoft/spack/bin/slmodules.sh -r deprecated -v

module purge
module load gromacs/5.1.2/intel-15.0.2

# Specify directories here
FILENAME=REPLACEME2
IDXNAME=REPLACEME3
di="init"
dm="min"
ne="nvteq"
de="npteq"
dr="relax"
md="md"

echo STARTING AT `date`

# NVT Equilibration
sed 's/RSTOPTION/no/g' $ne/template.$ne | sed 's/GENOPTION/yes/g' | sed 's/NSTEPOPTION/5000000/g' > $ne/$ne.mdp

srun -n 1 gmx_mpi grompp -f $ne/$ne.mdp -n ff/$IDXNAME.ndx -p $di/$FILENAME.top -c $dm/$dm.tpr -o $ne/$ne.tpr -t $dm/$dm.trr -r $dm/$dm.gro -maxwarn 1
srun gmx_mpi mdrun -v -deffnm $ne/$ne -cpo $ne/$ne.cpt -ntomp 1

sbatch CPUnpteq
